In [7]:
#!pip install ipywidgets

In [23]:
#!pip install kaggle

In [30]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import os
import kagglehub
import json


# from kaggle.api import KaggleApi
from dotenv import load_dotenv, dotenv_values

In [17]:
import os
import pandas as pd
from dotenv import load_dotenv, dotenv_values
import kagglehub

# 1. Force load the .env file explicitly by path
# (override=True ensures it overwrites any stale environment variables)
env_path = os.path.join(os.getcwd(), ".env")
loaded = load_dotenv(dotenv_path=env_path, override=True)

# 2. Debug & Verification Check
config = dotenv_values(env_path)
username = os.getenv("KAGGLE_USERNAME")
key = os.getenv("KAGGLE_KEY")

print(f".env file found at: {env_path}")
print(f".env loaded successfully: {loaded}")
print(f"KAGGLE_USERNAME: {username}")
if key:
    print(f"KAGGLE_KEY: {key[:4]}...{key[-4:]} (Masked for security)")
else:
    print("ERROR: KAGGLE_KEY is empty or missing in .env!")

# 3. Explicitly set env vars in python to be 100% sure
if username and key:
    os.environ["KAGGLE_USERNAME"] = username
    os.environ["KAGGLE_KEY"] = key

.env file found at: /Users/alhajidot/Documents/learning/Linear Algebra/RAG/.env
.env loaded successfully: True
KAGGLE_USERNAME: fagbamigbekehinde
KAGGLE_KEY: KGAT...6d0c (Masked for security)

In [19]:
import os
import json
import pandas as pd
from dotenv import load_dotenv
import kagglehub

# 1. Load environment variables from .env
load_dotenv(override=True)

username = os.getenv("KAGGLE_USERNAME")
key = os.getenv("KAGGLE_KEY")

if not username or not key:
    raise ValueError("KAGGLE_USERNAME or KAGGLE_KEY is missing from your .env file!")

# 2. Write the credentials to ~/.kaggle/kaggle.json directly
kaggle_dir = os.path.expanduser("~/.kaggle")
os.makedirs(kaggle_dir, exist_ok=True)

kaggle_json_path = os.path.join(kaggle_dir, "kaggle.json")
with open(kaggle_json_path, "w") as f:
    json.dump({"username": username, "key": key}, f)

# Set strictly required permissions for Kaggle API
os.chmod(kaggle_json_path, 0o600)

print(f"✅ Created {kaggle_json_path} for user: {username}")

✅ Created /Users/alhajidot/.kaggle/kaggle.json for user: fagbamigbekehinde

In [2]:
current_dir = os.getcwd()
print(f"My current directory is: {current_dir}")

My current directory is: /Users/alhajidot/Documents/learning/Linear Algebra/RAG

In [3]:
files = os.listdir(".")
print("Files and Folders:")
for file in files:
    print(f" - {file}")

Files and Folders:
 - rag_from_scratch_15_to_18.ipynb
 - rag_from_scratch_12_to_14.ipynb
 - rag_from_scratch_5_to_9.ipynb
 - agrochat.ipynb
 - rag_from_scratch_1_to_4.ipynb
 - README.md
 - .gitignore
 - .env
 - rag_from_scratch_10_and_11.ipynb

### Train Data

In [22]:
import os
import pandas as pd
from dotenv import load_dotenv
import kagglehub

# 1. Load variables from .env
load_dotenv(override=True)

# 2. Verify token is loaded in environment
token = os.getenv("KAGGLE_API_TOKEN")
if token:
    print(f"✅ KAGGLE_API_TOKEN loaded successfully ({token[:6]}...)")
else:
    print("❌ KAGGLE_API_TOKEN missing from environment!")

# 3. Download the competition data
download_path = kagglehub.competition_download("agricultural-extension-rag-smart-retrieval-for-farmers")

print("Files downloaded to:", download_path)

# 4. Load a CSV
qrels = pd.read_csv(os.path.join(download_path, "qrels_train.csv"))
qrels.head()

✅ KAGGLE_API_TOKEN loaded successfully (KGAT_5...)
Downloading to /Users/alhajidot/.cache/kagglehub/competitions/agricultural-extension-rag-smart-retrieval-for-farmers.archive...

100%|██████████| 71.3k/71.3k [00:00<00:00, 3.16MB/s]

Extracting files...
Files downloaded to: /Users/alhajidot/.cache/kagglehub/competitions/agricultural-extension-rag-smart-retrieval-for-farmers

   query_id  document_id  relevance
0         1            8        3.0
1         1            9        3.0
2         1           10        3.0
3         1            7        3.0
4         1            6        2.0


- /kaggle/input/competitions/agricultural-extension-rag-smart-retrieval-for-farmers/test_queries.csv
- /kaggle/input/competitions/agricultural-extension-rag-smart-retrieval-for-farmers/sample_submission.csv
- /kaggle/input/competitions/agricultural-extension-rag-smart-retrieval-for-farmers/documents.csv
- /kaggle/input/competitions/agricultural-extension-rag-smart-retrieval-for-farmers/dataset-metadata.json
- /kaggle/input/competitions/agricultural-extension-rag-smart-retrieval-for-farmers/train_queries.csv
- /kaggle/input/competitions/agricultural-extension-rag-smart-retrieval-for-farmers/qrels_train.csv
- /kaggle/input/competitions/agricultural-extension-rag-smart-retrieval-for-farmers/baseline_submission.csv

In [31]:


# 1. Load the JSON file into a Python dictionary
metadata_path = os.path.join(download_path, "dataset-metadata.json")

with open(metadata_path, "r") as f:
    dataset_metadata = json.load(f)

# 2. Inspect the dictionary
print("Keys:", dataset_metadata.keys())

# Pretty print the metadata structure
print(json.dumps(dataset_metadata, indent=2))

Keys: dict_keys(['title', 'id', 'subtitle', 'description', 'licenses', 'keywords', 'resources'])
{
  "title": "Agricultural Extension RAG Retrieval Dataset",
  "id": "YOUR_KAGGLE_USERNAME/agricultural-extension-rag",
  "subtitle": "A TREC/BEIR-style retrieval benchmark of farmer questions over an agricultural knowledge base",
  "description": "Document-retrieval benchmark for RAG systems. Given a smallholder farmer's question, rank the most relevant agricultural-extension documents. Features graded relevance (3/2/1/0), multiple relevant docs per query, and built-in hard negatives. Corpus blends an original synthetic backbone (CC0) with LLM-grounded rewrites of open-access CC-BY CGIAR sources. Leaderboard metric: nDCG@5. See DATACARD.md for full schema, evaluation, licensing, and build details.",
  "licenses": [
    {
      "name": "CC-BY-4.0"
    }
  ],
  "keywords": [
    "nlp",
    "information retrieval",
    "rag",
    "agriculture",
    "search",
    "ranking"
  ],
  "resources": [
    {
      "path": "documents.csv",
      "description": "Knowledge base / corpus to retrieve from (695 docs).",
      "schema": {
        "fields": [
          {
            "name": "document_id",
            "type": "string",
            "description": "Unique document id; use this in submissions."
          },
          {
            "name": "title",
            "type": "string",
            "description": "Document title."
          },
          {
            "name": "text",
            "type": "string",
            "description": "Document body (short extension factsheet)."
          },
          {
            "name": "source",
            "type": "string",
            "description": "Attributed publisher (FAO, CGIAR, Plantwise, IITA, ICRISAT, AGRA, ...)."
          },
          {
            "name": "crop",
            "type": "string",
            "description": "Primary crop, or '(general)' for soil/climate topics."
          },
          {
            "name": "country",
            "type": "string",
            "description": "Example country context."
          },
          {
            "name": "origin",
            "type": "string",
            "description": "'synthetic' (CC0 original) or 'llm_grounded' (rewritten from a CC-BY source)."
          },
          {
            "name": "source_url",
            "type": "string",
            "description": "Source link for grounded docs (blank for synthetic)."
          },
          {
            "name": "license",
            "type": "string",
            "description": "License of the underlying source."
          }
        ]
      }
    },
    {
      "path": "train_queries.csv",
      "description": "Training queries with their relevant docs (308 rows).",
      "schema": {
        "fields": [
          {
            "name": "query_id",
            "type": "integer",
            "description": "Unique query id (train ids start at 1)."
          },
          {
            "name": "query",
            "type": "string",
            "description": "The farmer's question."
          },
          {
            "name": "positive_docs",
            "type": "string",
            "description": "Space-separated document_ids with relevance >= 1 (convenience helper)."
          }
        ]
      }
    },
    {
      "path": "qrels_train.csv",
      "description": "Graded relevance labels for the training queries (4,194 rows).",
      "schema": {
        "fields": [
          {
            "name": "query_id",
            "type": "string",
            "description": "Query id."
          },
          {
            "name": "document_id",
            "type": "string",
            "description": "Document id."
          },
          {
            "name": "relevance",
            "type": "number",
            "description": "Graded relevance: 3 perfect, 2 relevant, 1 marginal, 0 hard negative."
          }
        ]
      }
    },
    {
      "path": "test_queries.csv",
      "description": "Test queries without answers; what you score against (200 rows).",
      "schema": {
        "fields": [
          {
            "name": "query_id",
            "type": "integer",
            "description": "Unique query id (test ids start at 1001)."
          },
          {
            "name": "query",
            "type": "string",
            "description": "The farmer's question."
          }
        ]
      }
    },
    {
      "path": "sample_submission.csv",
      "description": "Exact submission format, long (1,000 rows = 200 queries x 5). Row order per QueryId is the predicted ranking.",
      "schema": {
        "fields": [
          {
            "name": "QueryId",
            "type": "string",
            "description": "Test query id."
          },
          {
            "name": "DocumentId",
            "type": "string",
            "description": "A retrieved document id; row order within each query is the rank (best first)."
          }
        ]
      }
    },
    {
      "path": "baseline_submission.csv",
      "description": "TF-IDF baseline to beat (nDCG@5 = 0.551), long format. Row order per QueryId is the ranking.",
      "schema": {
        "fields": [
          {
            "name": "QueryId",
            "type": "string",
            "description": "Test query id."
          },
          {
            "name": "DocumentId",
            "type": "string",
            "description": "A retrieved document id; row order within each query is the rank (best first)."
          }
        ]
      }
    },
    {
      "path": "DATACARD.md",
      "description": "Full dataset documentation: task, schema, evaluation, licensing, and build process."
    }
  ]
}

In [26]:
train_queries = pd.read_csv(os.path.join(download_path, "train_queries.csv"))
train_queries.head()

   query_id                                              query positive_docs
0         1  How do I cope with flooding and excess rain on...    8 9 10 7 6
1         2  How can I adapt my farming to flooding and exc...    8 9 10 7 6
2         3  How does flooding and excess rain affect my cr...    6 8 9 10 7
3         4  What is the risk of flooding and excess rain t...    6 8 9 10 7
4         5     How do I manage bacterial leaf blight in rice?      40 36 38

In [25]:
documents = pd.read_csv(os.path.join(download_path, "documents.csv"))
documents.head()

,document_id,title,text,source,crop,country,origin,source_url,license
0,1,Drought and erratic rainfall: the risk to crops,Drought and erratic rainfall and its impact on...,FAO,(general),Kenya,synthetic,NaN,synthetic (CC0)
1,2,Adapting to drought and erratic rainfall (Guin...,Adapting to drought and erratic rainfall in th...,IITA,(general),Tanzania,synthetic,NaN,synthetic (CC0)
2,3,Adapting to drought and erratic rainfall (High...,Adapting to drought and erratic rainfall in th...,ICRISAT,(general),Nigeria,synthetic,NaN,synthetic (CC0)
3,4,Adapting to drought and erratic rainfall (Humi...,Adapting to drought and erratic rainfall in th...,FAO,(general),Mali,synthetic,NaN,synthetic (CC0)
4,5,Adapting to drought and erratic rainfall (Sahel),Adapting to drought and erratic rainfall in th...,FAO,(general),Tanzania,synthetic,NaN,synthetic (CC0)

In [24]:
test_queries = pd.read_csv(os.path.join(download_path, "test_queries.csv"))
test_queries.head()

   query_id                                              query
0      1001  How do I cope with drought and erratic rainfal...
1      1002  How can I adapt my farming to drought and erra...
2      1003  How does drought and erratic rainfall affect m...
3      1004  What is the risk of drought and erratic rainfa...
4      1005         How do I cope with heat stress on my farm?

In [27]:
baseline_submission = pd.read_csv(os.path.join(download_path, "baseline_submission.csv"))
baseline_submission.head()

   QueryId  DocumentId
0     1001           1
1     1001           2
2     1001           4
3     1001           3
4     1001           5

In [28]:
sample_submission = pd.read_csv(os.path.join(download_path, "sample_submission.csv"))
sample_submission.head()

   QueryId  DocumentId
0     1001           1
1     1001           2
2     1001           3
3     1001           4
4     1001           5